{
 "title": "Docker Swarm",
 "description": "Docker Swarm stacks and services metrics",
 "tags": [
  "prometheus",
  "docker",
  "home"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": { "query": "node_uname_info" } },
   {
    "name": "stack_namespace",
    "label": "Stack",
    "query": {
     "query": "query_result(count(container_last_seen{container_label_com_docker_stack_namespace=~\".+\"}) by (container_label_com_docker_stack_namespace))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(node_load1)" }
   ]
  },
  {
   "title": "Stacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", instance=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100 - sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node_id\"}[$__interval]) * 100) by (instance) / count(node_cpu_seconds_total{mode=\"user\",instance=~\"$node_id\"}) by (instance))",
     "legendFormat": "CPU"
    },
    {
     "expr": "max(100 - sum((node_memory_MemAvailable_bytes{instance=~\"$node_id\"} / node_memory_MemTotal_bytes{instance=~\"$node_id\"}) * 100) by (instance) / count(node_memory_MemAvailable_bytes{instance=~\"$node_id\"}) by (instance))",
     "legendFormat": "MEMORY"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", instance=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[5m])) "
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node_id\"}[$__interval]) * 100) / count(node_cpu_seconds_total{mode=\"user\",instance=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes{instance=~\"$node_id\"} / node_memory_MemTotal_bytes{instance=~\"$node_id\"}) * 100) / count(node_memory_MemAvailable_bytes{instance=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/\",instance=~\"$node_id\"} / node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$node_id\"}) * 100) / count(node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((((node_filesystem_size_bytes{instance=~\"$node_id\",fstype!=\"tmpfs\"} - node_filesystem_avail_bytes{instance=~\"$node_id\",fstype!=\"tmpfs\"})) / node_filesystem_size_bytes{instance=~\"$node_id\",fstype!=\"tmpfs\"}) * 100) by (instance, mountpoint)",
     "legendFormat": "{{ instance }} - {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node_id\"}[$__interval]) * 100) by (instance) / count(node_cpu_seconds_total{mode=\"user\",instance=~\"$node_id\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - sum((node_memory_MemAvailable_bytes{instance=~\"$node_id\"} / node_memory_MemTotal_bytes{instance=~\"$node_id\"}) * 100) by (instance) / count(node_memory_MemAvailable_bytes{instance=~\"$node_id\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Load (Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Load (Receive)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Service Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_stack_namespace=~\"$stack_namespace\",instance=~\"$node_id\"}[$__interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Containers # (by Service type)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) by (container_label_com_docker_stack_namespace)",
     "legendFormat": "{{ container_label_com_docker_stack_namespace }}"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"$stack_namespace\", instance=~\"$node_id\"}[$__interval])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "CPU usage by Container (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"$stack_namespace\", instance=~\"$node_id\"}[$__interval])) by (name)) * 100 ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_stack_namespace=~\"$stack_namespace\", instance=~\"$node_id\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Used {{ container_label_com_docker_swarm_service_name }}"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_stack_namespace=~\"$stack_namespace\", instance=~\"$node_id\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Cached {{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Memory usage by Container (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(container_memory_usage_bytes{container_label_com_docker_stack_namespace=~\"$stack_namespace\", instance=~\"$node_id\"}[$__interval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Traffic on Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Cluster IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval]) )",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{instance=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) ",
     "legendFormat": "Writes "
    }
   ]
  },
  {
   "title": "Network received by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Network transmitted by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  }
 ]
}