{
 "title": "Docker Swarm Nodes",
 "description": "Docker Swarm node overview",
 "tags": [
  "prometheus",
  "docker",
  "home"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": { "query": "node_uname_info" } }
  ]
 },
 "panels": [
  { "title": "$node_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node_id" },
  {
   "title": "CPU Idle",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node_id\"}[$__interval]) * 100) / count(node_cpu_seconds_total{mode=\"user\",instance=~\"$node_id\"})",
     "legendFormat": "SWARM"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes{instance=~\"$node_id\"} / node_memory_MemTotal_bytes{instance=~\"$node_id\"}) * 100) / count(node_memory_MemAvailable_bytes{instance=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/\",instance=~\"$node_id\"} / node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$node_id\"}) * 100) / count(node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$node_id\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100 - sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node_id\"}[$__interval]) * 100) by (instance) / count(node_cpu_seconds_total{mode=\"user\",instance=~\"$node_id\"}) by (instance))",
     "legendFormat": "CPU"
    },
    {
     "expr": "max(100 - sum((node_memory_MemAvailable_bytes{instance=~\"$node_id\"} / node_memory_MemTotal_bytes{instance=~\"$node_id\"}) * 100) by (instance) / count(node_memory_MemAvailable_bytes{instance=~\"$node_id\"}) by (instance))",
     "legendFormat": "MEMORY"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$node_id\"}[5m])) "
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", instance=~\"$node_id\", container_label_com_docker_stack_namespace=~\".+\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  }
 ]
}