{
 "title": "Traefik",
 "description": "Traefik dashboard (data from prometheus)",
 "tags": [
  "prometheus",
  "traefik",
  "home"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "label": "Entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  {
   "title": "global service health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"[5][0-9]{2}\"}[$__interval])) / sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"[1-5][0-9]{2}\"}[$__interval])) * 100",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum[$__interval])) by (service) / sum(rate(traefik_service_request_duration_seconds_count[$__interval])) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "average response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_sum[$__interval])) /\nsum(rate(traefik_entrypoint_request_duration_seconds_count[$__interval])) * 1000"
    }
   ]
  },
  {
   "title": "requests per second by service",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$__interval])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "requests by status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"1[0-9]{2}\"}[$__interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"2[0-9]{2}\"}[$__interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"3[0-9]{2}\"}[$__interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"4[0-9]{2}\"}[$__interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"5[0-9]{2}\"}[$__interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "success code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"[1-3][0-9]{2}\"}[$__interval])) by (entrypoint) ",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$__interval]))",
     "legendFormat": "Requests per 1s"
    }
   ]
  },
  {
   "title": "error code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"[4][0-9]{2}\"}[$__interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=~\"[5][0-9]{2}\"}[$__interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "requests per second by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$__interval])) by (service) ",
     "legendFormat": " {{service}}"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "service" },
  {
   "title": "$service response time",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum{service=\"$service\"}[$__interval])) /\nsum(rate(traefik_service_request_duration_seconds_count{service=\"$service\"}[$__interval])) * 1000"
    }
   ]
  },
  {
   "title": "$service return code",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_service_requests_total{service=\"$service\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "$service total requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\",code=~\"1[0-9]{2}\"}[$__interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\",code=~\"2[0-9]{2}\"}[$__interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\",code=~\"3[0-9]{2}\"}[$__interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\",code=~\"4[0-9]{2}\"}[$__interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\",code=~\"5[0-9]{2}\"}[$__interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "$service total requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}